rbac:
  enabled: true

loadBalancerIP: 35.235.46.248

dashboard:
  enabled: true
  domain: traefik.converge-app.net
  auth:
    basic:
      test: $apr1$G1y8Shty$sZ98XcXIBA1Bdtrohe5/41
    

ssl:
  enabled: true
  enforced: true

      
acme:
  enabled: true
  email: "converge.kjuulh@gmail.com"
  staging: false
  challengeType: "dns-01"
  persistence:
    enabled: false
  dnsProvider:
    name: gcloud
    gcloud:
      GCE_SERVICE_ACCOUNT_FILE: /secrets/gcloud-credentials.json
  # domains:
  #   enabled: true
  #   domainList:
  #     - main: "*.converge-app.net"
  #     - sans:
  #       - "converge-app.net"
  